name: enngene
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - graphviz=2.40.1
  - pandas=1.0.1=py36h0573a6f_0
  - matplotlib=3.1.3=py36_0
  - viennarna=2.4.14=py36h8b12597_0
  - tensorflow-estimator=2.1
  - tensorflow-gpu=2.1.0
  - pip=20.0.2=py36_0
  - pyyaml=5.3.1
  - pydot=1.4.1=py36_0
  - seaborn=0.10
  - pip:
    - streamlit==0.64
